version: "3.9"
services:
  blender-gui:
    build: .
    volumes:
      - ./addons:/workspace/addons
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /workspace
