name: Release Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - "feature/*"
      - main


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/blender/blender:3.6.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Blender build script
        run: |
          blender --background --python scripts/build_release.py

      - name: Create release zip
        run: |
          mkdir -p dist
          zip -r dist/release.zip output_folder/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
